version: '2'
services:
  asterisk:
    image: docksterisk_asterisk
    environment:
    - "TZ=Europe/Zurich"
    build:
      context: .
    network_mode: host # use "host" instead of ports directive if you want to open a large port range
    volumes:
    - ./conf:/etc/docksterisk
    - log:/var/log/asterisk   
    restart: always
 
volumes:
  log:

